### ISSUE TITLE
Gem intallation not working

### ISSUE THREAD

**Issue by ThoTischner** [theforeman/foreman_datacenter#13]
Hi,

we just tried to install the plugin via:

```
scl enable tfm bash
gem install --ignore-dependencies foreman_datacenter
```

Restart foreman.
No GUI Changes.
foreman_datacenter plugin not coming up on the about page in foreman.

So added:
```
[root@xxxx-xxxxxxPuppFo ~]# cat /usr/share/foreman/bundler.d/Gemfile.local.rb
gem 'foreman_datacenter'
```

Restarted foreman again now the Datacenter menu is coming up.

But when i click on some element:
```
Oops, we're sorry but something went wrong PG::Error: ERROR: relation "sites" does not exist LINE 1: SELECT "sites".* FROM "sites" ^ : SELECT "sites".* FROM "sites"
```
So it seems the database was not populated.

Also tried
```
foreman-rake assets:precompile
```

That aborts with the error:
```
rake aborted!
ArgumentError: Invalid option: copyright
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/uglifier-4.1.8/lib/uglifier.rb:149:in block in initialize
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/uglifier-4.1.8/lib/uglifier.rb:148:in each
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/uglifier-4.1.8/lib/uglifier.rb:148:in initialize
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:47:in new
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:47:in initialize
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:24:in new
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:24:in instance
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:28:in call
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in call_processor
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in block in call_processors
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in reverse_each
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in call_processors
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in load_from_unloaded
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in block in load
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in fetch_asset_from_dependency_cache
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in load
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in block in initialize
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in yield
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in load
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in find_asset
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in find_all_linked_assets
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:134:in block in find
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:133:in each
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:133:in find
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:168:in compile
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in block (3 levels) in define
/opt/rh/sclo-ror42/root/usr/share/gems/gems/sprockets-3.5.2/lib/rake/sprocketstask.rb:147:in with_logger
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in block (2 levels) in define
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

Versions:

```
[root@xxxxxxxxxxxxxxxx ~]# gem list | grep foreman
foreman-tasks (0.10.9)
foreman-tasks-core (0.2.4)
foreman_bootdisk (10.0.2)
foreman_datacenter (0.1.49)
foreman_dhcp_browser (0.0.7)
foreman_hooks (0.3.14)
foreman_setup (5.0.0)
hammer_cli_foreman (0.11.0)

[root@xxxxxxxxxxxxxxx ~]# rpm -qa | grep foreman
foreman-proxy-1.16.0-1.el7.noarch
tfm-rubygem-foreman-tasks-core-0.2.4-1.fm1_16.el7.noarch
foreman-installer-1.16.1-1.el7.noarch
foreman-release-scl-3-1.el7.noarch
tfm-rubygem-foreman_dhcp_browser-0.0.7-3.fm1_11.el7.noarch
tfm-rubygem-foreman-tasks-0.10.9-1.fm1_16.el7.noarch
foreman-debug-1.16.0-1.el7.noarch
foreman-postgresql-1.16.0-1.el7.noarch
tfm-rubygem-hammer_cli_foreman-0.11.0-1.el7.noarch
tfm-rubygem-foreman_setup-5.0.0-1.fm1_13.el7.noarch
foreman-1.16.0-1.el7.noarch
foreman-cli-1.16.0-1.el7.noarch
tfm-rubygem-foreman_bootdisk-10.0.2-1.fm1_16.el7.noarch
foreman-selinux-1.16.0-1.el7.noarch
foreman-vmware-1.16.0-1.el7.noarch
tfm-rubygem-foreman_hooks-0.3.14-1.fm1_16.el7.noarch
foreman-release-1.16.0-1.el7.noarch

[root@xxxxxxxxxxxxxxxxxxx ~]# gem list | grep ugli
uglifier (4.1.8)

[root@xxxxxxxxxxxxxxxxxxx ~]# rpm -qa | grep node
nodejs-6.12.3-1.el7.x86_64

```

Thanks,
Thomas

**Comment by ThoTischner** [comment]
Okay we made some progress:

Needed to update sprockets and installed some more gems + rh-ruby22-ruby-devel:
```
  765  gem install sprockets
  769  gem install --ignore-dependencies sass
  771  gem install --ignore-dependencies sass-listen
  773  gem install --ignore-dependencies rb-fsevent
  775  gem install --ignore-dependencies rb-inotify
  777  gem install --ignore-dependencies ffi

Added:
[centos-sclo-sclo-rh]
name=CentOS-7 - SCLo sclo ruby22
baseurl=http://mirror.centos.org/centos/7/sclo/x86_64/rh/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo

to /etc/yum.repos.d/CentOS-SCLo-scl.repo

  807  yum install rh-ruby22-ruby-devel
  810  gem install --ignore-dependencies ffi

foreman-rake assets:precompile worked now =)

  815  gem uninstall foreman_datacenter
  816  gem install --ignore-dependencies foreman_datacenter
```

But still got the error:

```
Oops, we're sorry but something went wrong PG::Error: ERROR: relation "sites" does not exist LINE 1: SELECT "sites".* FROM "sites" ^ : SELECT "sites".* FROM "sites"
```

**Comment by Zenya** [comment]
@disappear89 please execute migration command
plugin contains db changes so it should be also executed

`RAILS_ENV=production rake db:migrate`

**Comment by ThoTischner** [comment]
@Zenya 

That brings the error:

```
[root@xxxxxxxxxxxxxxxxxxxxx ~]# RAILS_ENV=production foreman-rake db:migrate
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x00000002c001c8>
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:664:in `block in method_missing'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `say_with_time'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:654:in `method_missing'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:416:in `method_missing'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/foreman_datacenter-0.1.49/db/migrate/20160727161914_create_sites.rb:1:in `<top (required)>'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:777:in `load_migration'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:773:in `migration'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1051:in `use_transaction?'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:958:in `block in migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `each'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:823:in `up'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:801:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x00000002c001c8>
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:664:in `block in method_missing'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:634:in `say_with_time'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:654:in `method_missing'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:416:in `method_missing'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/foreman_datacenter-0.1.49/db/migrate/20160727161914_create_sites.rb:1:in `<top (required)>'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:777:in `load_migration'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:773:in `migration'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1051:in `use_transaction?'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:959:in `block in migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `each'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:955:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:823:in `up'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:801:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by zdenekjanda** [comment]
hard to say what exactly is wrong here. installing from gem isnt fully documented anyway, .deb or .rpm builds should work. in any case, you have to fix DB migrations, either figuring out whats wrong or applying SQL changes found in foreman's migrations manually and then fixing migrations sql table

**Comment by whowell** [comment]
@disappear89 I had seemingly the same set of problems last week installing the datacenter plugin (Katello 3.4/Foreman 1.15.6). After resolving a set of gem dependency issues (can post if it is relevant to your 1.16 install), I also had to make modifications to the datacenter migration scripts. I can make and post diffs if that is easier, but in the meantime here is what I did to remove the troublesome bits

```
[root@foremandev1 migrate]# pwd
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/foreman_datacenter-0.1.49/db/migrate
[root@foremandev1 migrate]# for F in `ls`;do  sed -i ${F} -e 's/\[4.2\]//';done;

```


 I also had to include several gems in

`/usr/share/foreman/bundler.d/Gemfile.local.rb`

**Comment by ThoTischner** [comment]
Maybe the versions are to old?
```
[root@xxxxxxxxxxxxxxxxx ~]# scl enable tfm bash
[root@xxxxxxxxxxxxxxxxx ~]# gem list | grep active
activejob (4.2.5.1)
activemodel (4.2.5.1)
activerecord (4.2.5.1)
activerecord-session_store (0.1.2)
activesupport (4.2.5.1)
```

Is there already a RPM available for CentOS?

@whowell
Thanks, i will try this

**Comment by ThoTischner** [comment]
Juhuu it`s working now, thank you All @Zenya @zdenekjanda @whowell

**Comment by whowell** [comment]
awesome @disappear89 . FWIW, the fix in our environment specifically for

```
[root@xxxxxxxxxxxxxxxxxxxxx ~]# RAILS_ENV=production foreman-rake db:migrate
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x00000002c001c8>
```

was the following as and example (actually applied to all the datacenter/db/migrate, I just don't want to soil up the comments too much)

```
--- a/db/migrate/20160727161914_create_sites.rb
+++ b/db/migrate/20160727161914_create_sites.rb
@@ -1,4 +1,4 @@
-class CreateSites < ActiveRecord::Migration[4.2]
+class CreateSites < ActiveRecord::Migration
   def change
     create_table :sites do |t|
       t.string :name, limit: 50
```

**Comment by ThoTischner** [comment]
Okay, maybe the activerecord gem version is to old and it cant understand the class parameter?
But i dont wanted to install to much via gem, dont want to breake foreman ;)

Fyi i created this pull request: https://github.com/theforeman/foreman_datacenter/pull/14

**Comment by zdenekjanda** [comment]
@disappear89 many thanks for your contribution to documentation, i have merged it with more fixes. Closing this for now.
