### ISSUE TITLE
Plugin on Foreman 1.17.1 install fails

### ISSUE THREAD

**Issue by roflmao** [theforeman/foreman_datacenter#18]
OS: Ubuntu 16.04

```
09:52:13 [root@foreman01[GM]:~] $ apt-get install ruby-foreman-datacenter
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  foreman-compute foreman-ec2
The following NEW packages will be installed:
  foreman-compute foreman-ec2 ruby-foreman-datacenter
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/848 kB of archives.
After this operation, 945 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package foreman-compute.
(Reading database ... 86117 files and directories currently installed.)
Preparing to unpack .../foreman-compute_1.17.1-1_all.deb ...
Unpacking foreman-compute (1.17.1-1) ...
Selecting previously unselected package foreman-ec2.
Preparing to unpack .../foreman-ec2_1.17.1-1_all.deb ...
Unpacking foreman-ec2 (1.17.1-1) ...
Selecting previously unselected package ruby-foreman-datacenter.
Preparing to unpack .../ruby-foreman-datacenter_0.1.44_all.deb ...
Unpacking ruby-foreman-datacenter (0.1.44) ...
Setting up foreman-compute (1.17.1-1) ...
Setting up foreman-ec2 (1.17.1-1) ...
Setting up ruby-foreman-datacenter (0.1.44) ...
```

After restarting apache2:

```
2018-06-18T09:56:16  [app] [W] unknown class ForemanDatacenter::PowerPorts, ignoring
 | NameError: uninitialized constant ForemanDatacenter::PowerPorts
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:271:in `const_get'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:271:in `block in constantize'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `inject'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:267:in `constantize'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
 | /usr/share/foreman/app/models/filter.rb:88:in `get_resource_class'
 | /usr/share/foreman/app/models/filter.rb:116:in `resource_class'
 | /usr/share/foreman/app/models/filter.rb:123:in `granular?'
 | /usr/share/foreman/app/models/filter.rb:176:in `build_taxonomy_search'
 | /usr/share/foreman/app/models/filter.rb:166:in `inherit_taxonomies!'
 | /usr/share/foreman/app/models/filter.rb:160:in `enforce_inherited_taxonomies'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `block in make_lambda'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `catch'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:600:in `block in default_terminator'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:198:in `block in halting'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `block in invoke_before'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:507:in `invoke_before'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:130:in `run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `create_or_update'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:129:in `save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/validations.rb:44:in `save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:35:in `save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:308:in `block in save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:307:in `save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:42:in `save'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/associations/collection_association.rb:371:in `insert_record'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/associations/has_many_association.rb:34:in `insert_record'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:408:in `block in save_collection_association'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:401:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:401:in `save_collection_association'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:186:in `block in add_autosave_association_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:158:in `instance_eval'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/autosave_association.rb:158:in `block in define_non_cyclic_method'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:413:in `block in make_lambda'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:511:in `block in invoke_after'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:511:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:511:in `invoke_after'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:132:in `run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_update_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:344:in `_update_record'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/timestamp.rb:107:in `_update_record'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:563:in `create_or_update'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `block in create_or_update'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:336:in `create_or_update'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:162:in `save!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/validations.rb:50:in `save!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `block in save!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:313:in `save!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/suppressor.rb:46:in `save!'
 | /usr/share/foreman/app/models/role.rb:207:in `add_permissions!'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:101:in `block (2 levels) in include_permissions_for_role'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/audited-4.5.0/lib/audited/auditor.rb:283:in `without_auditing'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:98:in `block in include_permissions_for_role'
 | /usr/share/foreman/app/models/role.rb:234:in `ignore_locking'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:97:in `include_permissions_for_role'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:109:in `add_all_permissions_to_role'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:11:in `block in add_all_permissions_to_default_roles'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
 | /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
 | /usr/share/foreman/app/registries/foreman/plugin/rbac_support.rb:10:in `add_all_permissions_to_default_roles'
 | /usr/share/foreman/app/registries/foreman/plugin.rb:275:in `add_all_permissions_to_default_roles'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_datacenter-0.1.44/lib/foreman_datacenter/engine.rb:414:in `block (2 levels) in <class:Engine>'
 | /usr/share/foreman/app/registries/foreman/plugin.rb:67:in `instance_eval'
 | /usr/share/foreman/app/registries/foreman/plugin.rb:67:in `register'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_datacenter-0.1.44/lib/foreman_datacenter/engine.rb:20:in `block in <class:Engine>'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
 | /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
 | /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
 | /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
 | /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
 | /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
 | /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
 | /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
 | /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
 | /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
 | /usr/share/foreman/config/environment.rb:5:in `<top (required)>'
 | config.ru:3:in `require'
 | config.ru:3:in `block in <main>'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
 | config.ru:1:in `new'
 | config.ru:1:in `<main>'
 | /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
 | /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
 | /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
 | /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
 | /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
2018-06-18T09:56:16  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:19  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000b85ef98>
 | Did you mean?  alias_method)
2018-06-18T09:56:28  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:28  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:28  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:28  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:28  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:30  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:30  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:32  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000bd0eed0>
 | Did you mean?  alias_method)
2018-06-18T09:56:41  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:41  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:41  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:42  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:42  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:43  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:43  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:46  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000ad047d8>
 | Did you mean?  alias_method)
2018-06-18T09:56:55  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:55  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:55  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:55  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:55  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:57  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:57  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:56:59  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000bba0238>
 | Did you mean?  alias_method)
2018-06-18T09:57:08  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:08  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:08  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:08  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:08  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:10  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:10  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:12  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000aa32398>
 | Did you mean?  alias_method)
2018-06-18T09:57:20  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:21  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:21  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:21  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:21  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:23  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:23  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:25  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000aa447f0>
 | Did you mean?  alias_method)
2018-06-18T09:57:33  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:34  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:34  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:34  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:34  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:35  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:35  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:38  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000ac9c7f0>
 | Did you mean?  alias_method)
2018-06-18T09:57:46  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:46  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:46  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:47  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:47  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:48  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:49  [app] [I] Current user: foreman_admin (administrator)
2018-06-18T09:57:51  [app] [W] ForemanSlack: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000b8cd330>
 | Did you mean?  alias_method)
```

**Comment by Zenya** [comment]
hi
will check it

**Comment by roflmao** [comment]
Looks like the db migration fails:

```
10:07:56 [root@foreman01[GM]:/var/lib/foreman] $ foreman-rake db:seed
You have 36 pending migrations:
  20160727161914 CreateSites
  20160728123353 CreateRackGroups
  20160728143149 CreateRacks
  20160728161636 CreatePlatforms
  20160728162635 CreateDeviceRoles
  20160728163815 CreateManufacturers
  20160728164858 CreateDeviceTypes
  20160728171422 CreateDevices
  20160728194401 CreateDeviceInterfaces
  20160728195242 CreateDeviceInterfaceConnections
  20160804104103 CreateInterfaceTemplates
  20160804142618 CreateConsolePortTemplates
  20160804164301 CreatePowerPortTemplates
  20160805080626 CreateConsoleServerPortTemplates
  20160805084726 CreatePowerOutletTemplates
  20160805100411 CreateDeviceBayTemplates
  20160809091611 CreateDeviceBays
  20160809103211 CreatePowerOutlets
  20160809104325 CreatePowerPorts
  20160809112815 CreateConsoleServerPorts
  20160809113846 CreateConsolePorts
  20160816224805 CreateDeviceModules
  20160824212010 AddHostRefToDevices
  20160828200938 AddIpAddressToDeviceInterfaces
  20160905211522 CreateManagementDevices
  20160906205605 RenameFieldInManagementDevices
  20160909205537 AddNameIndexToRacks
  20160920221011 RemoveIndexFromDevices
  20170824122025 AddSideToDevice
  20170918202630 AddRacksizeToDevice
  20170922110137 CreateComments
  20170922174725 RenamingComments
  20170924194247 RenameDeviceCommentsColumn
  20170929101032 AddParentIdToComments
  20171001130802 FixParentIdColumnInComments
  20171004221349 AddUserIdToComments
Run `rails db:migrate` to update your database then try again.
10:08:10 [root@foreman01[GM]:/var/lib/foreman] $ foreman-rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSites < ActiveRecord::Migration[4.2]
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:525:in `inherited'
/usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_datacenter-0.1.44/db/migrate/20160727161914_create_sites.rb:1:in `<top (required)>'
/usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:962:in `load_migration'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:958:in `migration'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1305:in `use_transaction?'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1297:in `ddl_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSites < ActiveRecord::Migration[4.2]
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:525:in `inherited'
/usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_datacenter-0.1.44/db/migrate/20160727161914_create_sites.rb:1:in `<top (required)>'
/usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:962:in `load_migration'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:958:in `migration'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1305:in `use_transaction?'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1297:in `ddl_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by ekohl** [comment]
This can also be seen on git master with foreman develop.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman_datacenter/pull/19/commits/f94b8b5712c30a2812fb63609c3d323eb4e1ed57 was needed for me to even start up in development.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman_datacenter/pull/21 was also needed for me.
